typography_spectrum: 0.5469398542772979
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.9958604844287038
  rhythmicContrast: 0.3925850058440119
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Ram Rojas
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ram Rojas
description: Muralist and Painter
purpose: []
